### ISSUE TITLE
iOS Present Alert doesn't work in modal windows

### ISSUE THREAD

**Issue by dhaligas** [aritchie/userdialogs#156]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[x] iOS
[] Android
[] UWP
[] PCL

2) Please state the issue to the best of your ability below

iOS Present Alert doesn't work in Xamarin.Forms in Modals
The old version would use the top view controller to present the view controller

I extended the impl and changed Present to use top and it is working.

https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.iOS/UserDialogsImpl.cs#L219

**Comment by timbrand** [comment]
I confirm this issue.
Just for information, this is the error:
`Warning: Attempt to present <UIAlertController: 0x7bbfa800> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x7e579400> whose view is not in the window hierarchy!`
For the time being I'll go for the solution of @dhaligas , thanks for that!

**Comment by eL-Prova** [comment]
Is this problem solved in the latest version?

**Comment by sylvain-toptal** [comment]
I'm still getting this issue in 6.5.1.  The same VC is used in modals and in the root nav VC and it doesn't work when from the modal

**Comment by aritchie** [comment]
@sylvain-toptal I wouldn't use this in modals right now.

**Comment by sylvain-toptal** [comment]
Just realized the issue was me not passing a proper TopViewMethod in Init :
```
                UserDialogs.Init(() => Window.RootViewController);
```

**Comment by aritchie** [comment]
This is not something I'm ever going to "fix".  You can always control the top window detection function yourself as shown above
