### ISSUE TITLE
ToastConfig.Duration has no effect on iOS

### ISSUE THREAD

**Issue by highplains** [aritchie/userdialogs#98]
Changing this value does not effect the display time. I think the code has it hardcoded with a 3 second constant.

**Comment by aritchie** [comment]
This is fixed in 4.1.7 which I put live on nuget last night

**Comment by highplains** [comment]
Thank you!

**Comment by samukbg** [comment]
Hi, still not working for me... it's still like 1 second for each toast

**Comment by aritchie** [comment]
Are you using the latest version?  What are you doing just before and after you call for the toast?

**Comment by samukbg** [comment]
Ok i found the problem, I have a login form with a _userDialogs.ShowLoading after submit than a _userDialogs.HideLoading() to hide it after getting the response and then a toast to show a success message. It seems that the animations doesn't sync between each task

**Comment by supreettare** [comment]
Did you get a fix for this problem? 
If I do something like 

ShowLoading 
Await for a method 
HIde loading 
Show Toast -> This toast does not stay for the default 3 seconds but hides immediately. 

Is this a bug?

**Comment by aritchie** [comment]
Leave a delay between your loading/toast to allow animations to finish.

This isn't a bug with this library.  It is simply the nature of the platform workings here

**Comment by allanes87** [comment]
Hello @aritchie, firstly thanks for this library!
I have the same problem that @supreettare, in Android works well, but in IOS the toast does not stay for the default 3 seconds.

I left a delay between the loading and toast but the problem is not solved.

ShowLoading 
Await for a method 
HIde loading 
Thread.Sleep(milliseconds);
Show Toast

**Comment by aritchie** [comment]
A potential fix is out in 5.3.  If it doesn't fix the issue, you'll have to wait for 6.0 that is now in beta1
